[build]
  publish = "dist"
  command = "npm run build"

[functions]
  ignored_node_modules = ["sharp", "@img/sharp-libvips-linux-x64", "@img/sharp-libvips-linuxmusl-x64"]

[build.processing.html]
  pretty_urls = false
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
